<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span><ul class="toc-item"><li><span><a href="#Challenge-Large-Scale-Machine-Learning" data-toc-modified-id="Challenge-Large-Scale-Machine-Learning-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Challenge Large Scale Machine Learning</a></span><ul class="toc-item"><li><span><a href="#Authors:" data-toc-modified-id="Authors:-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Authors:</a></span><ul class="toc-item"><li><span><a href="#Kevin-Elgui-(kevin.elgui@gmail.com),-Pascal-Bianchi" data-toc-modified-id="Kevin-Elgui-(kevin.elgui@gmail.com),-Pascal-Bianchi-1.1.1.1"><span class="toc-item-num">1.1.1.1&nbsp;&nbsp;</span>Kevin Elgui (<a href="mailto:kevin.elgui@gmail.com" target="_blank">kevin.elgui@gmail.com</a>), Pascal Bianchi</a></span></li></ul></li><li><span><a href="#Geolocation-challenge" data-toc-modified-id="Geolocation-challenge-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Geolocation challenge</a></span></li></ul></li></ul></li><li><span><a href="#The-properties-of-the-dataset:" data-toc-modified-id="The-properties-of-the-dataset:-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>The properties of the dataset:</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Training-data:" data-toc-modified-id="Training-data:-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>Training data:</a></span></li><li><span><a href="#Test-data:" data-toc-modified-id="Test-data:-2.0.2"><span class="toc-item-num">2.0.2&nbsp;&nbsp;</span>Test data:</a></span></li></ul></li><li><span><a href="#The-performance-criterion¶" data-toc-modified-id="The-performance-criterion¶-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>The performance criterion¶</a></span></li></ul></li><li><span><a href="#Training-Data" data-toc-modified-id="Training-Data-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Training Data</a></span></li><li><span><a href="#Test-Data" data-toc-modified-id="Test-Data-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Test Data</a></span></li><li><span><a href="#Example-submission" data-toc-modified-id="Example-submission-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Example submission</a></span><ul class="toc-item"><li><span><a href="#Loading-and-investigate-the-data" data-toc-modified-id="Loading-and-investigate-the-data-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Loading and investigate the data</a></span><ul class="toc-item"><li><span><a href="#Data-Visualization-(requires-bokeh)" data-toc-modified-id="Data-Visualization-(requires-bokeh)-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Data Visualization (requires bokeh)</a></span></li></ul></li><li><span><a href="#Example-submission" data-toc-modified-id="Example-submission-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Example submission</a></span><ul class="toc-item"><li><span><a href="#Features-selection" data-toc-modified-id="Features-selection-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Features selection</a></span></li><li><span><a href="#Linear-Regression" data-toc-modified-id="Linear-Regression-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span>Linear Regression</a></span><ul class="toc-item"><li><span><a href="#Remark:" data-toc-modified-id="Remark:-5.2.2.1"><span class="toc-item-num">5.2.2.1&nbsp;&nbsp;</span>Remark:</a></span></li></ul></li><li><span><a href="#Notation" data-toc-modified-id="Notation-5.2.3"><span class="toc-item-num">5.2.3&nbsp;&nbsp;</span>Notation</a></span><ul class="toc-item"><li><span><a href="#Now-it's-your-turn.-Good-luck-!--:)" data-toc-modified-id="Now-it's-your-turn.-Good-luck-!--:)-5.2.3.1"><span class="toc-item-num">5.2.3.1&nbsp;&nbsp;</span>Now it's your turn. Good luck !  :)</a></span></li></ul></li></ul></li></ul></li></ul></div>

# Introduction

## Challenge Large Scale Machine Learning

### Authors: 
#### Kevin Elgui (kevin.elgui@gmail.com), Pascal Bianchi

### Geolocation challenge

The goal of this challenge is to develop a system which tries to perform a geolocation of connected devices within an IoT Network.

The challenge will have two phases. Please read the below information carefully.

In the first phase of the challenge, you will be provided a training dataset which contains the raw messages and their corresponding coordinates. We will also provide you a validation dataset, which only contains the raw messages. The labes of the validation set will not be provided. In this phase, you will train your system based on this data and the ranking in the challenge webpage will be based on your score obtained on the validation data.

The second phase of the challenge will start only a couple of hours before the deadline. Within this period, we will provide you the test set. You will need to run the algorithm that you developed on the first phase on this dataset and submit your predictions to the challenge webpage. Your final ranks will be determined on this dataset. Note that this phase will only last a couple of hours, which means that you will not be able to tune your algorithm on this dataset.

# The properties of the dataset:

### Training data:

The training set contains raw messages (lines) and their labels (GPS-position). There are about 1M messages in this dataset. Each message is of size 1 x 21, where 21 is the number of message descriptors. For each message there is a label, a couple (latitude, longitude).

### Test data:

The test dataset only contains raw messages. There are about 10e5 messages in this dataset, where the format is the same as before. The labels of this dataset will not be provided. Within the first phase, your ranks will be calculated based on this dataset.

## The performance criterion¶

The question of a suitable criterion for evaluation is tough. In practice, in order to suit industrial requirements, we evaluate your prediction throught the 90% quantile of the error vector, which is computed as follows:
$$ error = d_V(pred, true),$$ where $d_V$ is the Vincenty distance between to GPS-coordinates. Finally:

$$ criterion =  error_{(90\%)}$$
In other words, this criterion corresponds to the max error distance made by your model on $90\%$ of the test set.
The lower the score, the better the performance.

# Training Data

Raw messages + Labels: https://www.dropbox.com/s/mvm878ub2qz2rz8/train_dataset.csv

# Test Data

Raw messages:  https://www.dropbox.com/s/rmv69jeigyao8xb/test_dataset.csv

# Example submission

In [1]:
%reset -f

In [3]:
%matplotlib inline
import numpy as np
import sys
import os
import pandas as pd
import matplotlib.pyplot as plt
import math
from geopy.distance import vincenty

## Loading and investigate the data

In [ ]:
%%time
## This is only basestation information. Comment if you don't want to use it. 
bs_data = pd.read_csv('../Data/Train/datamart_production_basestations_history.csv', sep=';', low_memory=False)

In [19]:
bs_distinct_velue = bs_data.apply(lambda x: len(x.unique()))
print(bs_distinct_velue)

site_status                            5
sno_name                              36
date_valid                           191
ai_lastedittime                    10337
ai_lastedittype                        2
ai_type                                2
antennagain                           10
attenuation                           27
attenuationdirect                    112
attenuationindirect                  119
azimuth                               76
basefreq                               9
bitrate                                2
bsid_hex                            9298
cableloss                             79
capabilities                          54
cavityfilterversion                   11
cavityfilterversion_text              11
cavityfilterversiondescription         9
commtime                            9409
conn                                   3
conn_text                              3
conns                                  5
creationtime                        1105
dead                                   2
decommtime                          1473
description                         6318
diagnosticmode                         2
dlkcf                                 10
dlkgain                               17
                                   ...
mastequipmentdescription               6
model                                  6
muted                                  2
name                               10906
noncompliantactivity                   2
objid                               9298
power                                  1
preamp1                                2
preamp2                                1
protocol                               3
ramlog                                 2
restarttime                       136561
servicecoverage                        3
servicecoverage_text                   3
simplesite                         27410
siteid                              9008
splatradius                           15
state                                  3
state_text                             3
tilt                                   6
type                                   3
type_text                              3
version_campaignid                   380
version_campaignstatus                 4
version_classname                      1
version_current                       26
version_planned                        6
waintingforcbit                        2
warrantystarttime                    448
wwanmode                               2
Length: 91, dtype: int64

In [16]:
bs_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1561100 entries, 0 to 1561099
Data columns (total 91 columns):
site_status                       1561100 non-null int64
sno_name                          1561100 non-null object
date_valid                        1561100 non-null object
ai_lastedittime                   1561100 non-null object
ai_lastedittype                   1561100 non-null int64
ai_type                           855053 non-null float64
antennagain                       1561100 non-null float64
attenuation                       1561098 non-null float64
attenuationdirect                 67127 non-null float64
attenuationindirect               67087 non-null float64
azimuth                           1561100 non-null float64
basefreq                          1561100 non-null int64
bitrate                           1561100 non-null int64
bsid_hex                          1561100 non-null object
cableloss                         1561100 non-null float64
capabilities                      1557176 non-null object
cavityfilterversion               1055180 non-null float64
cavityfilterversion_text          1055180 non-null object
cavityfilterversiondescription    5705 non-null object
commtime                          1561100 non-null object
conn                              1557051 non-null float64
conn_text                         1557051 non-null object
conns                             1557038 non-null object
creationtime                      1561100 non-null object
dead                              1561100 non-null object
decommtime                        253539 non-null object
description                       1155450 non-null object
diagnosticmode                    1561100 non-null object
dlkcf                             1561100 non-null int64
dlkgain                           1561100 non-null int64
downlinkauthorized                1561100 non-null object
downlinkenabled                   1561100 non-null object
downtime                          0 non-null float64
elevation                         1561100 non-null int64
envloss                           1561100 non-null float64
exploitationinfo                  75005 non-null object
exported                          1561100 non-null object
fields                            1561100 non-null int64
firstcommtime                     765430 non-null object
gainflag                          1561100 non-null object
globalcoverageenable              1561100 non-null object
groupid                           1561100 non-null object
gsmoptions_delay                  307 non-null float64
gsmoptions_phonenumber            307 non-null float64
hwversion                         1556849 non-null object
installer                         918456 non-null object
ip                                1557703 non-null object
keepalive                         1561100 non-null int64
last                              1558648 non-null object
lastping                          1558642 non-null object
lat                               1561100 non-null float64
lifecyclestatus                   1561100 non-null int64
lifecyclestatus_text              1561100 non-null object
lna_version                       1561100 non-null object
lnabypass                         1561100 non-null object
lnagain                           1561100 non-null float64
lnanoisefigure                    1561100 non-null float64
lng                               1561100 non-null float64
macrochannel                      1561100 non-null int64
makercode                         1496773 non-null object
mastequipment                     1561100 non-null int64
mastequipmentdescription          1161 non-null object
model                             1502974 non-null object
muted                             1561100 non-null object
name                              1561100 non-null object
noncompliantactivity              1561100 non-null object
objid                             1561100 non-null int64
power                             1561100 non-null int64
preamp1                           1561100 non-null int64
preamp2                           1561100 non-null int64
protocol                          1561100 non-null int64
ramlog                            1561100 non-null int64
restarttime                       1557051 non-null object
servicecoverage                   25608 non-null float64
servicecoverage_text              25608 non-null object
simplesite                        1561100 non-null object
siteid                            1561100 non-null object
splatradius                       77196 non-null float64
state                             1561100 non-null int64
state_text                        1561100 non-null object
tilt                              1561100 non-null float64
type                              1561100 non-null int64
type_text                         1561100 non-null object
version_campaignid                206399 non-null object
version_campaignstatus            206399 non-null float64
version_classname                 0 non-null float64
version_current                   1558508 non-null object
version_planned                   8254 non-null object
waintingforcbit                   1561100 non-null object
warrantystarttime                 1496773 non-null object
wwanmode                          1561100 non-null int64
dtypes: float64(22), int64(21), object(48)
memory usage: 1.1+ GB

In [15]:
bs_data.describe()

,site_status,ai_lastedittype,ai_type,antennagain,attenuation,attenuationdirect,attenuationindirect,azimuth,basefreq,bitrate,...,protocol,ramlog,servicecoverage,splatradius,state,tilt,type,version_campaignstatus,version_classname,wwanmode
count,1.561100e+06,1.561100e+06,855053.0,1.561100e+06,1.561098e+06,67127.000000,67087.000000,1.561100e+06,1.561100e+06,1.561100e+06,...,1.561100e+06,1.561100e+06,25608.000000,77196.000000,1.561100e+06,1.561100e+06,1.561100e+06,206399.000000,0.0,1.561100e+06
mean,1.370539e+00,4.799436e-01,0.0,5.268474e+00,1.514939e+00,177.235573,176.090043,3.696081e+00,8.661714e+08,2.068926e-02,...,2.978229e+00,1.999849e+00,0.139331,76.113205,1.159145e+00,-3.748459e-03,1.734802e-02,1.950402,NaN,8.381628e-01
std,3.397209e+00,4.995977e-01,0.0,1.079770e+00,8.398415e+00,103.672756,104.526217,2.858149e+01,5.134379e+07,1.423419e-01,...,1.474031e-01,1.229442e-02,0.346299,60.650540,5.173656e-01,1.918652e-01,1.373780e-01,0.257592,NaN,3.683015e-01
min,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,8.100000e+06,0.000000e+00,...,1.000000e+00,1.000000e+00,0.000000,0.000000,1.000000e+00,-1.000000e+01,0.000000e+00,0.000000,NaN,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.0,5.000000e+00,0.000000e+00,83.390000,89.060000,0.000000e+00,8.681300e+08,0.000000e+00,...,3.000000e+00,2.000000e+00,0.000000,50.000000,1.000000e+00,0.000000e+00,0.000000e+00,2.000000,NaN,1.000000e+00
50%,0.000000e+00,0.000000e+00,0.0,5.000000e+00,0.000000e+00,185.000000,180.000000,0.000000e+00,8.681300e+08,0.000000e+00,...,3.000000e+00,2.000000e+00,0.000000,50.000000,1.000000e+00,0.000000e+00,0.000000e+00,2.000000,NaN,1.000000e+00
75%,0.000000e+00,1.000000e+00,0.0,5.000000e+00,0.000000e+00,265.000000,270.000000,0.000000e+00,8.681300e+08,0.000000e+00,...,3.000000e+00,2.000000e+00,0.000000,100.000000,1.000000e+00,0.000000e+00,0.000000e+00,2.000000,NaN,1.000000e+00
max,1.500000e+01,1.000000e+00,0.0,2.200000e+01,1.000000e+02,359.000000,357.640000,3.596700e+02,1.296100e+09,1.000000e+00,...,3.000000e+00,2.000000e+00,1.000000,200.000000,3.000000e+00,2.000000e+00,2.000000e+00,2.000000,NaN,1.000000e+00

In [13]:
bs_data.head()

,site_status,sno_name,date_valid,ai_lastedittime,ai_lastedittype,ai_type,antennagain,attenuation,attenuationdirect,attenuationindirect,...,type,type_text,version_campaignid,version_campaignstatus,version_classname,version_current,version_planned,waintingforcbit,warrantystarttime,wwanmode
0,0,SIGFOX_Spain_Cellnex,2018-01-01 00:00:00,2017-03-30 09:30:01,0,NaN,5.0,0.0,NaN,NaN,...,0,Standard,NaN,NaN,NaN,v4.3.6,NaN,f,2014-02-25 23:00:00,0
1,0,SIGFOX_Spain_Cellnex,2018-01-01 00:00:00,2017-12-07 13:36:30,0,NaN,5.0,0.0,NaN,NaN,...,0,Standard,NaN,NaN,NaN,v4.3.6,NaN,f,2015-01-11 23:00:00,1
2,0,SIGFOX_UK_Arqiva,2018-01-01 00:00:00,2017-06-19 08:45:07,1,NaN,0.0,0.0,NaN,NaN,...,0,Standard,NaN,NaN,NaN,v4.1.9,NaN,t,2014-09-08 22:00:00,1
3,0,SIGFOX_UK_Arqiva,2018-01-01 00:00:00,2017-08-11 12:57:49,0,NaN,8.0,0.0,NaN,NaN,...,0,Standard,597992443c878975c85f30f1,2.0,NaN,v4.3.6,NaN,t,2014-03-11 23:00:00,1
4,0,SIGFOX_France,2018-01-01 00:00:00,2017-08-11 09:19:38,0,NaN,5.0,0.0,NaN,NaN,...,0,Standard,NaN,NaN,NaN,v4.3.6,NaN,f,2014-10-22 22:00:00,1

In [10]:
bs_data.bsid.unique()

array([ 3915, 13240, 13249, 10985,  1121,  2293,  2849, 17121,  1241,
       15623, 10744,  8442], dtype=int64)

In [6]:
dtypes = ['string', 'float', 'float', np.int64, 'string',  ]
train_messages_df = pd.read_csv('../Data/Toy/db_toy.csv', sep=';', )
train_messages_df.head()

,messageid,latitude,longitude,did,did_hex,time_msg,time_ux,time_ux_client,motion,speed,...,radius,datepart,seqnumber,dtid,nseq,rssi,bsid_hex,bsid,snr,freq
0,5a4b36a612f1431c0bbcfe5a,49.150979,2.584248,2158065,20EDF1,2018-01-02 07:37:10,1514878630000,1514878240000,t,127.0,...,NaN,2018-01-02,536,5491a93b9336908c3b1b4c70,0,-139,F4B,3915,11.740000,868136469
1,5a4b36a612f1431c0bbcfe5a,49.150979,2.584248,2158065,20EDF1,2018-01-02 07:37:10,1514878630000,1514878240000,t,127.0,...,NaN,2018-01-02,536,5491a93b9336908c3b1b4c70,0,-137,33B8,13240,13.980000,868137053
2,5a4b36a612f1431c0bbcfe5a,49.150979,2.584248,2158065,20EDF1,2018-01-02 07:37:10,1514878630000,1514878240000,t,127.0,...,NaN,2018-01-02,536,5491a93b9336908c3b1b4c70,0,-125,33C1,13249,26.580000,868136944
3,5a4b370f12f1431c0bbda371,49.368966,2.647366,5140063,4E6E5F,2018-01-02 07:38:55,1514878735000,1514878300000,f,0.0,...,NaN,2018-01-02,3581,5491a93b9336908c3b1b4c70,0,-139,2AE9,10985,12.210000,868109404
4,5a4b3958e541cd714dedf24b,49.244820,3.094714,2154347,20DF6B,2018-01-02 07:48:40,1514879320000,1514879320000,f,0.0,...,NaN,2018-01-02,3922,5491a93b9336908c3b1b4c70,0,-100,461,1121,51.560001,868188574

In [ ]:
db_toy_df.columns

In [ ]:
#train_messages_fname = '~/Data/Train/train_dataset.csv'

#Please fill 
train_messages_fname = '../Data/Train/train_dataset.csv'
assert(os.path.exists(train_messages_fname))
train_messages_df = pd.read_csv(train_messages_fname, sep=',')

## Test messages_fname

In [7]:
train_messages_df.head()

,messageid,latitude,longitude,did,did_hex,time_msg,time_ux,time_ux_client,motion,speed,...,radius,datepart,seqnumber,dtid,nseq,rssi,bsid_hex,bsid,snr,freq
0,5a4b36a612f1431c0bbcfe5a,49.150979,2.584248,2158065,20EDF1,2018-01-02 07:37:10,1514878630000,1514878240000,t,127.0,...,NaN,2018-01-02,536,5491a93b9336908c3b1b4c70,0,-139,F4B,3915,11.740000,868136469
1,5a4b36a612f1431c0bbcfe5a,49.150979,2.584248,2158065,20EDF1,2018-01-02 07:37:10,1514878630000,1514878240000,t,127.0,...,NaN,2018-01-02,536,5491a93b9336908c3b1b4c70,0,-137,33B8,13240,13.980000,868137053
2,5a4b36a612f1431c0bbcfe5a,49.150979,2.584248,2158065,20EDF1,2018-01-02 07:37:10,1514878630000,1514878240000,t,127.0,...,NaN,2018-01-02,536,5491a93b9336908c3b1b4c70,0,-125,33C1,13249,26.580000,868136944
3,5a4b370f12f1431c0bbda371,49.368966,2.647366,5140063,4E6E5F,2018-01-02 07:38:55,1514878735000,1514878300000,f,0.0,...,NaN,2018-01-02,3581,5491a93b9336908c3b1b4c70,0,-139,2AE9,10985,12.210000,868109404
4,5a4b3958e541cd714dedf24b,49.244820,3.094714,2154347,20DF6B,2018-01-02 07:48:40,1514879320000,1514879320000,f,0.0,...,NaN,2018-01-02,3922,5491a93b9336908c3b1b4c70,0,-100,461,1121,51.560001,868188574

In [9]:
y_train = train_messages_df[['latitude', 'longitude']]
X_train = train_messages_df.drop(['latitude','longitude'], 1)

In [10]:
train_messages_df.longitude.head()

0    2.584248
1    2.584248
2    2.584248
3    2.647366
4    3.094714
Name: longitude, dtype: float64

### Data Visualization (requires bokeh)

In [11]:
y_train.describe()

          latitude    longitude
count  5177.000000  5177.000000
mean     49.387622     2.837561
std       0.164544     0.460238
min      45.591995     1.985870
25%      49.381142     2.784360
50%      49.406927     2.808846
75%      49.429600     2.873020
max      50.032618    21.095268

In [16]:
## If you have bokeh installed, you can uncomment the last commands. 

sys.path.append('../Utils/')

from plot_map import PlotMap
PlotMap(y_train)

## Example submission

In the following, we will train a simple regressor on toy data.

In [56]:
## Please fill 

#test_messages_fname = #'path_to_your_folder/Data/Train/train_dataset.csv'
test_messages_fname = '../Data/Test/test_dataset.csv'
assert(os.path.exists(test_messages_fname))
test_messages_df = pd.read_csv(test_messages_fname, sep=',', low_memory=False, usecols=np.arange(1, 22), dtype={'freq':np.float64})

In [57]:
test_messages_df.head()

,messageid,did,did_hex,time_msg,time_ux,time_ux_client,motion,speed,altitude,nb_satellites,...,radius,datepart,seqnumber,dtid,nseq,rssi,bsid_hex,bsid,snr,freq
0,5b3d6f8b12f1430bafe5dea8,3595036,36DB1C,2018-07-05 01:08:27,1530752907000,1.530753e+12,NaN,NaN,NaN,NaN,...,250.0,2018-07-05,3114,5afbe2c59058c264249ac174,1,-137,6B5E,27486,9.600000,868146966.0
1,5a71c7dacf554f3e0eaa6a40,8198175,7D181F,2018-01-31 13:42:50,1517406170000,1.517406e+12,NaN,NaN,NaN,NaN,...,NaN,2018-01-31,1224,59817a859058c23f6f4d2708,2,-135,7C4,1988,15.910000,868198620.0
2,5b337a18cf554f36d27b28ec,3595036,36DB1C,2018-06-27 11:50:48,1530100248000,1.530100e+12,NaN,NaN,NaN,NaN,...,0.0,2018-06-27,3463,5afbe2c59058c264249ac174,2,-136,27A7,10151,13.950000,868103977.0
3,5b38067f12f14319b605c5a8,3595222,36DBD6,2018-06-30 22:38:55,1530398335000,1.530398e+12,NaN,NaN,NaN,NaN,...,0.0,2018-06-30,1096,5afbe2c59058c264249ac174,2,-132,6B5E,27486,16.959999,868168038.0
4,5b1a8584cf554f36d29574e2,3595036,36DB1C,2018-06-08 13:32:52,1528464772000,1.528465e+12,NaN,NaN,NaN,NaN,...,74.0,2018-06-08,3047,5afbe2c59058c264249ac174,0,-107,D56,3414,19.650000,868062772.0

### Features selection

In this example, we propose a simple feature matrix $X$ such that :

$$\begin{cases} X[i,j] &= 1 &\text{ if the $j^{th}$ basestation received the $i^{th}$ message}, \\
 X[i,j] &= 0, &\text{otherwise}. \end{cases} $$

For the project, you are free to chose other parameters for your model.

In [44]:
## Please run the cell
## --------------------

features_of_interest = {"features_of_interest": ['freq'],
"target":["latitude", "longitude"]}

dict_of_gby = {'rssi': ['bsid'],
                'freq': ['bsid'],
                'latitude_bs': ['bsid'],
                'longitude_bs': ['bsid'],
                'latitude': [''],
                'longitude': [''],
                'speed': [''],
                'dtid': [''], 
                'did': [''],
              }

In [45]:
X_train_ = X_train.iloc[:4000]
y_train_ = y_train.iloc[:4000]

In [46]:
%%time
## On training Data in would take an hour. Be patient, you can have a break. 

from features_builder import _build_features_dict, my_parser

(feature_dict, feature_name), (target_dict, target_name)  = _build_features_dict(X_train_, features_of_interest)
res = my_parser(X_train_, y_train_, feature_dict, target_dict, features_of_interest)
X = pd.DataFrame(res['X'].toarray(), columns=res['dict_X'])
y = pd.DataFrame(res['y'].toarray(), columns=res['dict_y'])
print(res.keys())
msg_list = res['msg_list']

Features of interest:  ['freq']
Target:  ['latitude', 'longitude']
Nb of base stations:  12
Nb of unique DeviceId train:  247
dict_keys(['dict_X', 'dict_y', 'X', 'y', 'msg_list'])
Wall time: 3.64 s

In [49]:
res['dict_X']

{'freq3915': 0,
 'freq13249': 1,
 'freq13240': 2,
 'freq17121': 3,
 'freq1241': 4,
 'freq10985': 5,
 'freq10744': 6,
 'freq8442': 7,
 'freq2849': 8,
 'freq1121': 9,
 'freq2293': 10,
 'freq15623': 11}

In [54]:
pd.DataFrame(res['X'].A).describe()

,0,1,2,3,4,5,6,7,8,9,10,11
count,2059.0,2059.0,2059.0,2059.0,2059.0,2059.0,2059.0,2059.0,2059.0,2059.0,2059.0,2059.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from evaluation import *

In [ ]:
Xf_train, Xf_test, y_train, y_test, msg_list_train, msg_list_test = train_test_split(X, y, msg_list, test_size=0.25, random_state=50)

In [ ]:
reg = LinearRegression()
reg.fit(Xf_train, y_train)  

pred = pd.DataFrame(reg.predict(Xf_test), columns=res['dict_y'])
pred['messageid'] = msg_list_test
y_test['messageid'] = msg_list_test

print('The criterion on the testing data : %.2f km' % criterion(df2dict(pred), df2dict(y_test)))

#np.savetxt('path_of_your_choice/pred_test.txt', pred)

#### Remark: 
The criterion is about 10 km. Well done !

### Notation 
After having upload your file pred_test.txt on the server, you will be ranked w.r.t the criterion. 
The score which is assigned to you is computed on half of the test set. This corresponds to the public score. 
On the other half, you are assigned a private score. 

Your final score will take into account these two scores. Thus, your final rank may differ slightly from the one you see on the leader board.

#### Now it's your turn. Good luck !  :)